### ISSUE TITLE
Breaks scaffolding and farmland blocks

### ISSUE THREAD

**Issue by lockieluke** [JimiIT92/BetterSnowierSnow#4]
**Describe the bug**
When the plugin is enabled:
- Scaffolding blocks don't collapse when the first block is broken
- Farmland blocks don't turn back to dirt blocks when being jumped on

**Expected behavior**
- These should all work

**Screen recording**
https://cdn.discordapp.com/attachments/289587909051416579/1191876440682135632/Export-1704235705934.mp4

**Versions (please complete the following information):**
 - Minecraft: [e.g. 1.16.4] 1.20.4
 - Plugin [e.g. 1.0] Latest version

**Comment by JimiIT92** [comment]
Hi, sorry for the really late response, got involved with a lot of stuff privately. Anyway the issue has now been solved thanks to the [TRUEC0DER Pull Request](https://github.com/JimiIT92/BetterSnowierSnow/pull/3), you can get the latest version for 1.20.4 from Modrinth here: [https://modrinth.com/plugin/better-snowier-snow/version/1.4-1.20.4](https://modrinth.com/plugin/better-snowier-snow/version/1.4-1.20.4)
