### ISSUE TITLE
Make it compatible with Folia

### ISSUE THREAD

**Issue by HydrolienF** [JimiIT92/BetterSnowierSnow#5]
**Is your feature request related to a problem? Please describe.**
Not realy, I have a Folia server and I would like to have this plugin on it.

**Describe the solution you'd like**
Plugin work iwth folia without removing any features.

**Describe alternatives you've considered**
I might make it compatible with Folia, miself if I find enoth time. If so I will send a pull request.

**Additional context**
See https://papermc.io/software/folia

**Comment by JimiIT92** [comment]
Hi, I was out of town for the past months, sorry if I only answer this now.

Unfortunately I don't know what Folia is, so yeah, if you have the knowledge to make it work with that feel free to do so and send a PR :D
