### ISSUE TITLE
1.21/1.21.1 support

### ISSUE THREAD

**Issue by MrSmi1ey** [JimiIT92/BetterSnowierSnow#7]
**Is your feature request related to the issue? Please describe.**
A clear and concise description of the problem. [ please add support for 1.21/1.21.1 ]

**Describe your desired solution**
A clear and concise description of what you want.

**Describe alternatives you have considered**
A clear and concise description of any alternative solutions or features,
which you were considering.

**Additional context**

**Comment by JimiIT92** [comment]
Hi, sorry I  was out of town for the past months.
1.21 support will come soon, stay tuned ;)

**Comment by JimiIT92** [comment]
Hi, a new update for Minecraft 1.21.1 has been released :D
https://modrinth.com/plugin/better-snowier-snow/version/VBvCXiEW
